# Site
repository: cyrillknecht/cyrillknecht.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Cyrill Knecht
title: Master's Student in EE & IT @ ETH Zurich
email: cyrknech [at] student [dot] ethz [dot] ch
website: cyrillknecht.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  cyrillknecht
linkedin_username: cyrill-david-knecht


# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/cv_photo.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Cyrill. I'm a Master's student in Electrical Engineering and Information Technology at ETH Zurich.
  I'm interested in machine learning, software engineering and data science.
  
  ğŸ‘· ğŸš§ **This will be my personal website and portfolio.
  It is still under construction, so please excuse any errors or missing content .** ğŸš§

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ETH Zurich
        caption: 2022 - 2024 (expected)
        sub_title: MSc Electrical Engineering and Information Technology
        quote: >
        description: | # this will include new lines to allow paragraphs
          Main focus on Machine Learning, Software Engineering and Data Science.
          Secondary focus on Automatic Control.
          
          Most Relevant Courses:
          - [Probabilistic Artificial Intelligence](https://www.vorlesungen.ethz.ch//Vorlesungsverzeichnis/lerneinheit.view?lerneinheitId=147370&semkez=2021W&ansicht=LEHRVERANSTALTUNGEN&lang=en)
          - [Deep Learning](https://www.vorlesungen.ethz.ch//Vorlesungsverzeichnis/lerneinheit.view?semkez=2021W&ansicht=ALLE&lerneinheitId=148055&lang=en)
          - [Image Analysis and Computer Vision](https://www.vorlesungen.ethz.ch//lerneinheitPre.do?semkez=2021W&lerneinheitId=146800&lang=en)
          - [Robot Learning](https://www.vorlesungen.ethz.ch//Vorlesungsverzeichnis/lerneinheit.view?semkez=2022S&ansicht=KATALOGDATEN&lerneinheitId=161281&lang=en)
          - [Big Data for Engineers](https://www.vorlesungen.ethz.ch//lerneinheitPre.do?semkez=2018S&lerneinheitId=122247&lang=en)
          - [Software Engineering](https://www.vorlesungen.ethz.ch//Vorlesungsverzeichnis/lerneinheit.view?lerneinheitId=136949&semkez=2020S&ansicht=KATALOGDATEN&lang=de)


      - layout: left
        title: ETH Zurich
        caption: 2018 - 2022
        sub_title: BSc Electrical Engineering and Information Technology
        quote: >
        description: | # this will include new lines to allow paragraphs
          Broad Focus on Electrical Engineering and Information Technology.
          
          Most Relevant Courses:
          - [Introduction to Machine Learning](https://www.vorlesungen.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lerneinheitId=167629&semkez=2023S&ansicht=LEHRVERANSTALTUNGEN&lang=en)
          - [Computer Engineering](https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&lerneinheitId=167541&semkez=2023S&ansicht=LEHRVERANSTALTUNGEN&)
          - [Computer Science II](https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&lerneinheitId=172243&semkez=2023W&ansicht=LEHRVERANSTALTUNGEN&)
          - [Computer Science I](https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&lerneinheitId=157782&semkez=2022S&ansicht=LEHRVERANSTALTUNGEN&)
          

      - layout: left
        title: Kantonsschule Baden
        caption: 2013 - 2017
        sub_title: Matura (Swiss High School Diploma) 5.3/6.0
        quote: >
        description: | # this will include new lines to allow paragraphs
          Focus on Business and Law.


  - title: A little more about me # Title for the section
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in machine learning and software engineering some of my other interests and hobbies are:
      - â›·ï¸ Skiing 
      - ğŸ“š Literature 
      - ğŸ‹ï¸ Fitness 
      - ğŸ Roundnet 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
